### ISSUE TITLE
Time sometimes goes out of sync

### ISSUE THREAD

**Issue by hemanta212** [sidbelbase/undistracted-me#21]
Great addon, been using for some months now in firefox and suddenly the time went out of sync. 

![image](https://user-images.githubusercontent.com/25475894/156313277-6eed4ab8-6d02-41de-b4f1-690cfb794a63.png)

The issue got fixed once I disabled and re-enabled the extension.

**Comment by sidbelbase** [comment]
hello mate, glad you liked it :)

Also, do you still have this issue? I have actually used the `Asia/Kathmandu` timezone as default wherever this addon is installed; making sure the issues like these won't trouble us again, I tested installing in my firefox as well. I'm opening this issue, if this issue still persists please continue with this thread.

**Comment by hemanta212** [comment]
I don't think I can reproduce this anymore after it got fixed through disabling/reenabling the extension. It just happened randomly one day (kinda weird since Asia/Kathmandu should have worked). So I don't think we can track the cause, unfortunately. Feel free to close this issue.
